### ISSUE TITLE
Convert ub

### ISSUE THREAD

**Issue by ughserrano** [markelekdotcom/color-ramp-converter#2]
Python: Traceback (most recent call last):
  File "C:\Users\YOURUSERNAME\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\color-ramp-converter-main\src\panels.py", line 53, in draw
    addon_prefs = get_addon_prefs()
  File "C:\Users\YOURUSERNAME\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\color-ramp-converter-main\src\functions.py", line 41, in get_addon_prefs
    return bpy.context.preferences.addons['color-ramp-converter'].preferences
KeyError: 'bpy_prop_collection[key]: key "color-ramp-converter" not found'

![image](https://github.com/markelekdotcom/color-ramp-converter/assets/129196485/3e6d515c-0c8d-4862-87e9-d8efd6dc1451)

**Comment by markelekdotcom** [comment]
- Please rename the folder "color-ramp-converter-main" to "**color-ramp-converter**" 
So the path looks like this: 
"C:\\Users\YOURUSERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\**color-ramp-converter**"

- Also ensure that the source files are directly located inside the "color-ramp-converter" folder, so the **"\_\_init\_\_.py"** file is inside that folder (not inside a second folder, etc.)

![image](https://github.com/markelekdotcom/color-ramp-converter/assets/11351295/38644944-3ce4-4be2-9298-5c94531ab579)

Hope this helps!
