### ISSUE TITLE
does it support gltf export?

### ISSUE THREAD

**Issue by clicktodev** [markelekdotcom/color-ramp-converter#4]
i installed this addon thinking it could make color ramp compatible with gltf export but apparently it still doesn't work.

**Comment by markelekdotcom** [comment]
The addon utilizes Blender's native nodes, including the Color Ramp, and is unrelated to the export process.

Unfortunately, as far as I know, there's no straightforward way to directly export procedural nodes like the Color Ramp to glTF without first converting them into a texture.
https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html

To make the Color Ramp compatible with glTF exports, you'll typically need to follow the standard process of UV mapping and baking the procedural textures into image files. 

A potential future solution might involve MaterialX as part of the USD exporter:
https://projects.blender.org/blender/blender/issues/125781
